# Generated by Django 4.2.3 on 2023-07-11 05:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_remove_user_is_superuser_user_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^((\\+?\\d{0,4})?\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{3}\\)?)\\s?-?\\s?(\\(?\\d{4}\\)?)?)?$",
                        "Invalid phone number.",
                    )
                ],
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="user",
            unique_together={("phone_number", "email")},
        ),
    ]
