repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-added-large-files
        args: ["--maxkb=500"]
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: debug-statements
    -   id: detect-private-key
    -   id: name-tests-test
        args: ["--django"]
    - id: trailing-whitespace
    - id: flake8
    - id: requirements-txt-fixer
    - id: no-commit-to-branch
-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args: ["--line-length=100"]
        language_version: python3.10
-   repo: local
    hooks:
      - id: isort
        name: isort-local
        entry: isort
        language: python
        types: [python]
        exclude: .+/(settings|migrations)/.+
        pass_filenames: true
      - id: missing-migrations
        name: missing-migrations-local
        entry: python manage.py makemigrations --check
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: Check mypy static types match
        entry: mypy-check.sh
        pass_filenames: true
        language: script
        types: [file]
      - id: bandit
        name: Check security issues
        entry: bandit -x "tests,factories.py,conftest.py,migrations,node_modules" -r .
        language: system